[package]
name = "types"
version = "0.1.0"
authors = ["elpinal <elpinal@users.noreply.github.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"
rand = "0.6.5"
